# Generated by Django 3.0 on 2020-10-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='customer',
            field=models.CharField(choices=[('RC', 'Организация производитель'), ('RCD', 'Организация перевозчик'), ('PD', 'Частный перевозчик')], max_length=3, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type_organization',
            field=models.CharField(choices=[('IP', 'ИП'), ('OOO', 'ООО'), ('PD', 'Частный перевозчик')], max_length=3, verbose_name='Вид деятильности'),
        ),
    ]
