# Generated by Django 3.0 on 2020-10-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_drivers', '0002_auto_20201016_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registcompdriver',
            options={'verbose_name': 'Сведения о компании перевозчике', 'verbose_name_plural': 'Сведения о компании перевозчике'},
        ),
        migrations.AlterModelOptions(
            name='registcustomer',
            options={'verbose_name': 'Сведения о компании производителе', 'verbose_name_plural': 'Сведения о компании производителе'},
        ),
        migrations.RemoveField(
            model_name='registcompdriver',
            name='count',
        ),
        migrations.RemoveField(
            model_name='registcompdriver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registcompdriver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registcompdriver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registcompdriver',
            name='rating',
        ),
        migrations.AddField(
            model_name='registcompdriver',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_drivers.UserProfile', verbose_name='Организация перевозчик'),
            preserve_default=False,
        ),
    ]
