# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""
Django settings for truck_driver project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from django.urls import reverse_lazy
import os
from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOGIN_REDIRECT_URL = reverse_lazy('app_drivers:base')
LOGOUT_REDIRECT_URL = reverse_lazy('app_drivers:base')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'account',
    'phonenumber_field',
    'django_email_verification', 
    'debug_toolbar',
    'app_drivers',
]

# PHONENUMBER_DEFAULT_REGION = 'RU'
# PHONENUMBER_DB_FORMAT = 'RU'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'account.middleware.LocaleMiddleware',
    'account.middleware.TimezoneMiddleware'    

]

ROOT_URLCONF = 'truck_driver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.account',

            ],
        },
    },
]

API_KEY_DISTANCE_METRIX = os.getenv('API_KEY_DISTANCE_METRIX'),

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'app_drivers.EmailBackend.CustomBackend',
]
TITLE = 'Подтверждение почты'

DEFAULT_FROM_EMAIL = 'danger-2403@mail.ru'
EMAIL_ACTIVE_FIELD  = 'is_active' 
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_SERVER  = 'smtp.mail.ru' 
EMAIL_PORT  =  2525 
EMAIL_ADDRESS  = 'danger-2403@mail.ru' 
EMAIL_FROM_ADDRESS  =  'danger-2403@mail.ru'
EMAIL_PASSWORD  =  os.getenv('EMAIL_PASSWORD') 
EMAIL_MAIL_SUBJECT  =  TITLE
EMAIL_MAIL_HTML  =  'mail_body.html' 
#EMAIL_MAIL_PLAIN  =  'mail_body.txt' 
EMAIL_PAGE_TEMPLATE  =  'confirm_template.html'
#EMAIL_PAGE_DOMAIN = 'http://mydomain.com/'
EMAIL_PAGE_DOMAIN = 'http://localhost:8000'
#ACCOUNT_EMAIL_UNIQUE = True
#ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = True

WSGI_APPLICATION = 'truck_driver.wsgi.application'

SITE_ID = 3

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'truck_driver',
        'USER' : 'postgres',
        'PASSWORD' : os.getenv(PASSWORDDB),
        'HOST' : '127.0.0.1',
        'PORT' : '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

INTERNAL_IPS = [
    '127.0.0.1',
]

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'truck_driver/static',)
]

MEDIA_DIR = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'truck_driver/media')


CRISPY_TEMPLATES_PACK = 'bootstrap4'
